import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import "./globals_postprocess.css"



export const metadata: Metadata = {
  title: "NextTodo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-base-300 w-full h-full scroll-smooth"  cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
